version: '3'
services:
  postgres13:
    image: postgres:13
    command: postgres -c 'max_connections=200'
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/data:/var/lib/postgresql/data
      - ./data/init:/opt/init
    environment:
      - POSTGRES_USER=darc
      - POSTGRES_PASSWORD=darc
    networks:
      postgres13_net:

networks:
  postgres13_net:
    ipam:
      driver: default

